language: node_js
node_js:
- lts/*
before_script:
- yarn install --pure-lockfile
deploy:
  provider: npm
  email: dmitry@itis.cs.msu.ru
  skip_cleanup: true
  api_key:
    secure: "hBIZXndUMdLkXYMJuZ+5B4GuCx42G8mywUoe6iS8tuVSm6TvrWi/AMbNxw003qtyPP6/6bXd+8p+EqkK68B6x2J9n/YkVIgyhA5wxoR033JW0LIu4NR2Nu8u0JQUiFm+BjBjUBF0Jr0uBoNxoxLlOlsLjxHIQvkiuB3pzkZ5Q3MWX6eTTMLLDOAg8qDD4beunyEPrZ29u3FWO4qGDqWFCkak5eJ+UU0Vuapk0Bw/13UxQyvqmEjVTvirSNOkXwkLnQi4j3t1hB52mMFJRoC9Ule2fhLBI9AEJb6nJGclzbVwpeeTEGtLGBbMxqHQBRfqZdkt8YoUbmPNmHo3PuiT+K7MEGxZZLbtH9xEPthC/tfrWNrNLlqeQ+Osg96x8kEs7TDDCBDNAMrBAsB13zrdLPsVZrbrsRVxthDlTSbA4u4LjcxBGN1EcTGkQSnVRTL8g1Itl/O10b3wve6bDAWeeqt47pCAZeUerpKM9eO+SQ9p32YEU95iaCIJoKJuCKNobdPFuC5dfNUzQG5DqwRNHECG70qqYCcgySWFLQlLXqk3Xf6QIK9XEWrZgOp+XWjJqClrmMcVwntwPczhQYQeO/IckWzDtoWDLB+NYL/hIdQhT8THxdEoRBDhukGtfJliur+E2LPSt2TLtBYcopv5Th4fH2xDAfA8/mBrXFgfnKY="
  on:
    tags: true
